package com.hospedaje.catalog.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDate;
import java.util.List;

/**
 * MongoDB document representing a rentable property
 * (hotel, apartment, room, etc.) in the accommodation catalog.
 * <p>
 * Each property has descriptive information, pricing, availability
 * windows, and a set of amenities.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "properties")
public class Property {

    /** Unique identifier — auto-generated by MongoDB as an ObjectId. */
    @Id
    private String id;

    /** Display name of the property (e.g., "Hotel Las Palmas"). */
    private String name;

    /** Full marketing description of the property. */
    private String description;

    /** City or region where the property is located. */
    private String location;

    /** Room type: SINGLE, DOUBLE, SUITE, PENTHOUSE. */
    private String roomType;

    /** List of amenities offered (e.g., WiFi, Pool, Gym). */
    private List<String> amenities;

    /** URLs of property images for display in the frontend. */
    private List<String> imageUrls;

    /** Nightly rate in USD. */
    private Double pricePerNight;

    /** Start of the availability window for bookings. */
    private LocalDate availableFrom;

    /** End of the availability window for bookings. */
    private LocalDate availableTo;

    /** Maximum number of guests the property can accommodate. */
    private Integer maxGuests;

    /** Whether the listing is currently active and bookable. */
    private Boolean active;
}
