spring.application.name=clon-mocky

# ========================
# Servidor
# ========================
server.port=8080

# ========================
# Base de Datos H2 (en memoria)
# ========================
spring.datasource.url=jdbc:h2:mem:clonmocky
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ========================
# JPA / Hibernate
# ========================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ========================
# JWT Configuration
# ========================
jwt.secret=Y2xvbi1tb2NreS1zZWNyZXQta2V5LXByYWN0aWNhLTIwMjUtc3ByaW5nLWJvb3Q=
jwt.expiration=60

# ========================
# Internacionalizacion (i18n)
# ========================
spring.messages.basename=messages
spring.messages.encoding=UTF-8
